homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('education/', views.education, name='education'),
    path('gallery/', views.gallery, name='gallery'),
    path('contact/', views.contact, name= 'contact'),
]

schedule/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.sched_list, name='sched_list'),
    path('new/', views.new_schedule, name='new_schedule'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.delete_schedule.as_view(), name='delete_schedule'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('schedules/', include('schedule.urls')),
]

urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('homepage.urls')),
    path('', include('schedule.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Schedule(models.Model):
    namaKegiatan = models.CharField(max_length=25)
    kategori = models.CharField(max_length=25)
    lokasi = models.CharField(max_length=25)
    tanggal = models.DateField()
    waktu = models.TimeField()

    def __str__(self):
        return self.namaKegiatan  

    def getTanggal(self):
        return self.tanggal.strftime("%d")

    def getBulan(self):
        return self.tanggal.strftime("%b")

    def getHari(self):
        return self.tanggal.strftime("%A")

    
    

    

schedule/forms.py
from django import forms
from .models import Schedule

class ScheduleForms(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ["namaKegiatan", "kategori", "lokasi", "tanggal", "waktu"]

homepage/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'Home.html')

def about(request):
    return render(request, 'About.html')

def education(request):
    return render(request, 'Education.html')

def gallery(request):
    return render(request, 'gallery.html')

def contact(request):
    return render(request, 'contact.html')

schedule/views.py
from django.shortcuts import render
from django.views import generic
from .models import Schedule
from .forms import ScheduleForms
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView

def sched_list(request):
    schedules = Schedule.objects.order_by('tanggal')
    return render(request, 'sched_list.html', {'schedules':schedules})

def new_schedule(request):
    if request.method == "POST":
        form = ScheduleForms(request.POST)
        if form.is_valid():
            schedule = form.save()
            schedule.save()
            return redirect('/schedules/')
    else:   
        form = ScheduleForms()
    return render(request, 'addschedule.html', {'form': form})

class delete_schedule(DeleteView):
    model = Schedule
    success_url = reverse_lazy('schedule:sched_list')

homepage/templates/About.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="About">
        <div id="About-title">
            <img src="{% static 'images/Ocit.png' %}" alt="">

            <h1>About Me</h1>
            <div id="rectangle1"></div>
            <p>Rasyid atau yang biasa disapa dengan Ocit merupakan seorang mahasiswa Fasilkom UI tahun kedua. Ia merupakan anak yang sangat senang mempelajari hal baru. Ocit juga hobi berenang loh, giginya patah saat sedang latihan loncat untuk lomba pertamanya. Dia juga senang membantu orang lain sampai lupa dengan dirinya sendiri.</p>
        </div>
    </div>
</body>
</html>

homepage/templates/Education.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Education">
        <div id="Education-title">
            <h1>Education & Experience</h1>
            <div id="rectangle2"></div>
        </div>

        <div id="riwayat">
            <ul>
                <li>SDIT Nurul Falah</li>
                <li>SMP Negeri 1 Kota Bekasi</li>
                <li>SMA Negeri 5 Kota Bandung</li>
                <li>Universitas Indonesia<p id="keterangan">Fakultas Ilmu Komputer</p></li>
            </ul>
        </div>

        <div id="pengalaman">
            <ul>
                <li>ScaleUp.id (Now Levilo.id)<p id="keterangan">Internship as Video Editor & Graphic Designer</p></li>
            </ul>
        </div>
    </div>
</body>
</html>

homepage/templates/Home.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div class="Home">
        <div id="Home-overlay">
            <p class="slideup">Hi,</p>
            <div id = "imocit">
                <h1 id=ocit>I Am Rasyid.</h1>
            </div>
            <div class="social">
                <ul>
                    <a href="https://www.instagram.com/siidrasyid" target="_blank"><li><i class="fab fa-instagram" aria-hidden="true"></i></li></a>
                    <a href="https://www.facebook.com/SSHBangOcit" target="_blank"><li><i class="fab fa-facebook-f" aria-hidden="true"></i></li></a>
                    <a href="https://www.linkedin.com/in/muhammadrasyid22/" target="_blank"><li><i class="fab fa-linkedin-in" aria-hidden="true"></i></li></a>
                    <a href="https://line.me/ti/p/n3DUuSuAx5" target="_blank"><li><i class="fab fa-line" aria-hidden="true"></i></li></a>
                </ul>
            </div> 
        </div>
        
    </div>

    
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Contact">
        <h1>Contact Me</h1>
        <div id="rectangle3"></div>
        <div class="social">
            <ul>
                <a href="https://www.instagram.com/siidrasyid" target="_blank"><li><i class="fab fa-instagram" aria-hidden="true"></i></li></a>
                <a href="https://www.facebook.com/SSHBangOcit" target="_blank"><li><i class="fab fa-facebook-f" aria-hidden="true"></i></li></a>
                <a href="https://www.linkedin.com/in/muhammadrasyid22/" target="_blank"><li><i class="fab fa-linkedin-in" aria-hidden="true"></i></li></a>
                <a href="https://line.me/ti/p/n3DUuSuAx5" target="_blank"><li><i class="fab fa-line" aria-hidden="true"></i></li></a>
            </ul>
        </div>

    </div>
</body>
</html>

homepage/templates/gallery.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    <script src="https://kit.fontawesome.com/629da8d65b.js" crossorigin="anonymous"></script>
    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
            <!-- Brand/logo -->
            <a class="navbar-brand" href="#">
                <img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
            </a>
                
            <!-- Links -->
            <div class = "collapse navbar-collapse justify-content-end">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    <div id="Gallery">
        <h1>Portofolio</h1>
        <div id="rectangle4"></div>
        <div class="Photo">
            <img class="photo1" src="{% static 'images/1.png' %}" width="400" height="400">
            <img class="photo2" src="{% static 'images/2.png' %}" width="400" height="400">
            <img class="photo3" src="{% static 'images/3.png' %}" width="400" height="400">
        </div>
    </div>
</body>
</html>

schedule/templates/addschedule.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
    </head>
    <body id="add">
    <nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
		<!-- Brand/logo -->
		<a class="navbar-brand" href="#">
			<img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
		</a>
			
		<!-- Links -->
		<div class = "collapse navbar-collapse justify-content-end">
			<ul class="nav navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:about' %}">About</a>
				</li>
				<li class="nav-item">

					<a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
				</li>
				<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
					</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
				</li>
			</ul>
		</div>
	</nav>
    
    <div class="containerAdd">
        <h2 id="titleAdd">New Schedule</h2>
        <form method="POST" class="post-form form-group">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
    </body>
</html>

schedule/templates/sched_list.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta name="viewport" content="width=device-width,initial-scale=1.0">
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="{% static 'css/StyleAll.css' %}">
	
</head>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<body>
	<nav class="navbar navbar-expand-sm bg-color navbar-dark fixed-top">
		<!-- Brand/logo -->
		<a class="navbar-brand" href="#">
			<img src="{% static 'images/ocitlogo.png' %}" alt="logo" style="width:50px;">
		</a>
			
		<!-- Links -->
		<div class = "collapse navbar-collapse justify-content-end">
			<ul class="nav navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:about' %}">About</a>
				</li>
				<li class="nav-item">

					<a class="nav-link" href="{% url 'homepage:education' %}">Education & Experience</a>
				</li>
				<li class="nav-item">
						<a class="nav-link" href="{% url 'homepage:gallery' %}">Portofolio</a>
					</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'schedule:sched_list' %}">Schedule</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
				</li>
			</ul>
		</div>
	</nav>
    <div>
    <h1 class="schedTitle">My Schedules</h1>
	<div id="rectangle1"></div>
    </div>
    
	<div id="list">
		{% for sched in schedules %}
		<div class="container">
			<div class="row row-striped">
				<div class="col-2 text-right">
					<h1 class="display-4"><span class="badge badge-secondary">{{sched.getTanggal}}</span></h1>
					<h2 class="bulannya">{{sched.getBulan}}</h2>
				</div>
			<div class="col-7">
				<h3 class="text-uppercase"><strong>{{sched.namaKegiatan}}</strong></h3>
				<ul class="list-inline">
				    <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{sched.getHari}}</li>
					<li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i>{{sched.tanggal}}</li>
					<li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i> {{sched.lokasi}}</li>
				</ul>
			</div>
			{% if user.is_authenticated %}
				<div class="col-3">
					<form action="{% url 'schedule:delete_schedule' sched.id %}" method="post" style="display:inline;">
					{% csrf_token %}
					<input type="hidden" name="sched_id" value"{{ sched.id }}"/>
					<button id="deletee" type="submit" class="btn btn-default btn-sm">Delete
					</button>
					</form>
				</div>
			{% endif %}
			
		</div>
	</div>  
  
{% endfor %}
</div>
{% if user.is_authenticated %}
<div class="page-header">
	<a href="{% url 'schedule:new_schedule' %}" class="btn">Add Schedule</a>
</div>
{% endif %}

</body>
</html>